# Generated by Django 3.0.4 on 2020-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200617_1126'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profile', to='orders.CODCategories', verbose_name='Categories for notifications'),
        ),
    ]
