# Generated by Django 3.0.4 on 2020-06-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chat', '0002_auto_20200617_1126'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='groupsuggestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='groupsuggestion',
            name='mass_order',
        ),
        migrations.RemoveField(
            model_name='massorder',
            name='author',
        ),
        migrations.RemoveField(
            model_name='massorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.RemoveField(
            model_name='order',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mass_order',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='order',
        ),
        migrations.DeleteModel(
            name='AllCity',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='GroupSuggestion',
        ),
        migrations.DeleteModel(
            name='MassOrder',
        ),
        migrations.DeleteModel(
            name='OperationCategories',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
