# Generated by Django 3.0.4 on 2020-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200617_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coddetail',
            name='Categories',
        ),
        migrations.AddField(
            model_name='codorder',
            name='Categories',
            field=models.ManyToManyField(blank=True, default='Default', related_name='CODDetail', to='orders.CODCategories', verbose_name='Categories'),
        ),
    ]
